In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
amazon_meta_df = pd.read_csv('datasets/amazon_beauty_metadata.csv')
amazon_reviews_df = pd.read_csv('datasets/amazon_beauty_reviews.csv')

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
amazon_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371345 entries, 0 to 371344
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      371345 non-null  int64
 1   overall         371345 non-null  float64
 2   verified        371345 non-null  bool
 3   reviewTime      371345 non-null  object
 4   reviewerID      371345 non-null  object
 5   asin            371345 non-null  object
 6   reviewerName    371293 non-null  object
 7   reviewText      370946 non-null  object
 8   summary         371134 non-null  object
 9   unixReviewTime  371345 non-null  int64
 10  vote            51899 non-null   object
 11  style           125958 non-null  object
 12  image           8391 non-null    object
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 34.4+ MB

In [4]:
amazon_meta_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32992 entries, 0 to 32991
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    32992 non-null  int64
 1   title         32991 non-null  object
 2   image         16609 non-null  object
 3   brand         17301 non-null  object
 4   rank          32615 non-null  object
 5   main_cat      32992 non-null  object
 6   asin          32992 non-null  object
 7   description   15191 non-null  object
 8   also_view     8155 non-null   object
 9   also_buy      6613 non-null   object
 10  price         11288 non-null  object
 11  similar_item  1305 non-null   object
 12  details       32836 non-null  object
 13  feature       269 non-null    object
 14  tech1         10 non-null     object
 15  date          19 non-null     object
dtypes: int64(1), object(15)
memory usage: 4.0+ MB

In [5]:
amazon_meta_df = amazon_meta_df.drop('details', axis=1)

In [6]:
brands = amazon_meta_df.groupby('brand')['title'].nunique()
print(brands)

brand
#Flashmob                                              1
#Healthy                                               2
#R5                                                    1
(3 Pack) NYC Ultra Moist Lipwear - Violet Shine ...    1
(Black Opal)                                           1
                                                      ..
younique                                               1
youthwaters                                            1
yoyomax                                                1
zila                                                   1
zonman                                                 1
Name: title, Length: 7893, dtype: int64

In [7]:
keywords = ['cleanser', 'moisturizer', 'oil', 'lotion', 'mask', 'aftershave', 'wash', 'scrub', 'shaving cream', 'deoderant', 'spf', 'face',
           'moisture', 'dry', 'oily', 'skincare', 'facial']

lowercase_cols = amazon_meta_df[['title','description', 'brand']]
lowercase_cols = lowercase_cols.apply(lambda x: x.astype(str).str.lower())
lowercase_cols.head()

,title,description,brand
0,workout headphones by arena essentials,nan,harpercollins
1,black diamond,['this is the new purple bottle that just came...,swedish beauty
2,"12 pc blue heaven kajal""herbal kajal with vita...","['a brand-new, unused, unopened, undamaged ite...",blue heave
3,the inheritance,"[""you have to wonder why there isn't a word in...",sunatoria
4,the listening cards,['the listening cards are an eloquent primer i...,listening planet

In [8]:
import string
table = str.maketrans("", "", string.punctuation)
vals = []
count = 0
products = []
for idx, j in lowercase_cols.iterrows():
    for val in j:
        val = val.translate(table)

for word in keywords:
    lowercase_cols["title-indx"] = lowercase_cols["title"].str.find(word)
    lowercase_cols["descript-indx"] = lowercase_cols["description"].str.find(word)

In [9]:
print(lowercase_cols["title-indx"].nunique())
print(lowercase_cols["descript-indx"].nunique())

121
218

In [10]:
products = lowercase_cols[(lowercase_cols['title-indx'] != -1) | (lowercase_cols['descript-indx'] != -1)]
products

,title,description,brand,title-indx,descript-indx
27,stick man tenth anniversary edition,['looking for a natural and effective way of r...,larivia essential,-1,574
28,new york city 2013 7x7 mini wall,['looking for a natural and effective way of r...,larivia essential,-1,574
33,cows 2014 calendar 18-month (multilingual edit...,['looking for a natural and effective way of r...,larivia essential,-1,574
110,norelco 5655x deluxe advantage wet/dry cordles...,"[""this water-resistant 6-watt electric razor h...",nan,-1,181
111,norelco 6885xl deluxe quadra action cord/cordl...,['this high-tech shaver comes with an lcd indi...,norelco,-1,728
...,...,...,...,...,...
32740,derma roller 0.25mm - facial skin care tool fo...,['stop spending thousands of dollars! forget a...,new body life,22,166
32786,"facial cleanser for acne prone skin, oily skin...",nan,nan,0,-1
32796,"cosmetic, makeup and beauty blender and facial...",nan,nan,40,-1
32875,derma roller 0.25mm - facial skin care tool fo...,['stop spending thousands of dollars! forget a...,new body life,22,166
32974,bial 24k golden beauty bar facial massager wat...,['1. power supply : d.c1.5v (one aa dry batter...,bial ex,27,-1

In [11]:
filtered_df = amazon_meta_df.merge(products, left_index=True, right_index=True)

In [12]:
filtered_df = filtered_df.drop(['brand_x', 'description_x', 'title-indx', 'descript-indx', 'Unnamed: 0', 'title_x'], axis=1)
filtered_df = filtered_df.rename(columns = {
    'brand_y': 'brand', 'title_y': 'title', 'description_y': 'description'
})
filtered_df

,image,rank,main_cat,asin,also_view,also_buy,price,similar_item,feature,tech1,date,title,description,brand
27,['https://images-na.ssl-images-amazon.com/imag...,"459,527inBeautyamp;PersonalCare(",All Beauty,140717455X,"['0545947898', '0142403873', '1407132326', 'B0...","['0142402753', '0142407542', '0142411388', 'B0...",NaN,NaN,NaN,NaN,NaN,stick man tenth anniversary edition,['looking for a natural and effective way of r...,larivia essential
28,['https://images-na.ssl-images-amazon.com/imag...,"1,782,789inBeautyamp;PersonalCare(",All Beauty,1421694778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,new york city 2013 7x7 mini wall,['looking for a natural and effective way of r...,larivia essential
33,['https://images-na.ssl-images-amazon.com/imag...,"1,788,643inBeautyamp;PersonalCare(",All Beauty,146500999X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cows 2014 calendar 18-month (multilingual edit...,['looking for a natural and effective way of r...,larivia essential
110,['https://images-na.ssl-images-amazon.com/imag...,"2,696,638inBeautyPersonalCare(",All Beauty,B000050B67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,norelco 5655x deluxe advantage wet/dry cordles...,"[""this water-resistant 6-watt electric razor h...",nan
111,['https://images-na.ssl-images-amazon.com/imag...,"2,639,859inBeautyPersonalCare(",All Beauty,B000050B65,"['B01B1O9DOM', 'B00JITDVD2', 'B01KXV16DK', 'B0...",NaN,NaN,NaN,NaN,NaN,NaN,norelco 6885xl deluxe quadra action cord/cordl...,['this high-tech shaver comes with an lcd indi...,norelco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32740,['https://images-na.ssl-images-amazon.com/imag...,"223,747inBeautyPersonalCare(",All Beauty,B01H4X9NQW,NaN,"['B07F1PDD27', 'B079NJ46M6', 'B07B9PLHSH', 'B0...",$8.97,NaN,NaN,NaN,NaN,derma roller 0.25mm - facial skin care tool fo...,['stop spending thousands of dollars! forget a...,new body life
32786,['https://images-na.ssl-images-amazon.com/imag...,"929,237inBeautyPersonalCare(",All Beauty,B01H74H0FE,NaN,"['B014XQFRD6', 'B01M0R05KS']",NaN,NaN,NaN,NaN,NaN,"facial cleanser for acne prone skin, oily skin...",nan,nan
32796,['https://images-na.ssl-images-amazon.com/imag...,"646,461inBeautyPersonalCare(",All Beauty,B01H7YN8UK,NaN,"['B00HF4M2GY', 'B075TD9S8M', 'B00PL3DK26', 'B0...",NaN,NaN,NaN,NaN,NaN,"cosmetic, makeup and beauty blender and facial...",nan,nan
32875,['https://images-na.ssl-images-amazon.com/imag...,"227,027inBeautyPersonalCare(",All Beauty,B01HDBMCJU,NaN,"['B07F1PDD27', 'B079NJ46M6', 'B07B9PLHSH', 'B0...",$8.97,NaN,NaN,NaN,NaN,derma roller 0.25mm - facial skin care tool fo...,['stop spending thousands of dollars! forget a...,new body life
32974,['https://images-na.ssl-images-amazon.com/imag...,"793,628inBeautyPersonalCare(",All Beauty,B01HI6M8H6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bial 24k golden beauty bar facial massager wat...,['1. power supply : d.c1.5v (one aa dry batter...,bial ex